analytics:
  twitter: null
  google: UA-62724694-1
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.32177
title: Filipe Santos
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.9085288278292865
  brandStrength: 0.625
  rhythmicContrast: 0.6290766329038888
  brandColors:
    - '#f40047'
    - '#ffe200'
    - '#40bcff'
    - '#1f1830'
    - '#ff6637'
  lightness: 0.6386932565364987
purpose: []
favicon: null
name: FISA
typography_spectrum: 0.25145
