typography_spectrum: 0.25145
color:
  brandColors:
    - '#f40047'
    - '#ffe200'
    - '#40bcff'
    - '#1f1830'
    - '#ff6637'
  brandStrength: 0.625
  lightness: 0.6386932565364987
  saturation: 0.9085288278292865
  rhythmicContrast: 0.6290766329038888
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.32177
analytics:
  google: UA-62724694-1
  facebook: '997355473646538'
  twitter: '@fisa67'
author:
  name: ''
  email: filipe@fisa.me
  url: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f96ef0a3-7fca-43fb-bf8b-0985a1316a54.png
name: ' '
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/82b0e0f9-715b-44be-a917-d9f4d7b635fe.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Filipe Santos
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://s3-us-west-2.amazonaws.com/the-grid-img/p/dab4302eb1de43b0e1cb7167c4a5f4993125208c.png">
    src: >-
      https://s3-us-west-2.amazonaws.com/the-grid-img/p/dab4302eb1de43b0e1cb7167c4a5f4993125208c.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://s3-us-west-2.amazonaws.com'
        name: .s3-us-west-2.amazonaws.com
        favicon: null
        domain: s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/eac1040f-ff5a-4255-ad58-86b496a6b42e.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/eac1040f-ff5a-4255-ad58-86b496a6b42e.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/0069e64e-5e83-4dbb-976b-00465193aafb.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/0069e64e-5e83-4dbb-976b-00465193aafb.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
purpose:
  - type: email
    url: 'mailto:filipe@fisa.me'
    label: '✉️ '
  - type: external
    url: 'https://www.instagram.com/fisa67'
    label: "\uD83D\uDCF7 "
github: true
description: "Aqui você vai encontrar tudo sobre a minha persona, gostos, influenzas e mais umas paradinhas ae… Vamos nessa?  \uD83D\uDC7B\uD83D\uDC7D\uD83E\uDD22\uD83D\uDE39\uD83D\uDC7E\uD83E\uDD16\uD83C\uDFA7  Para conhecer minhas habilidades e experiências profissionais, acesse o meu perfil do LinkedIn, me mande um E-mail ou me siga no IG. \uD83D\uDE18"
