name: fisa
favicon: null
layout_spectrum: 0.318407695973292
typography_spectrum: 0.2673686051275581
title: Filipe Santos
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-62724694-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6403238931670785
  lightness: 0.6386932565364987
  saturation: 0.9085288278292865
  rhythmicContrast: 0.6290766329038888
purpose: []
