name: FISA
favicon: null
layout_spectrum: 0.318407695973292
typography_spectrum: 0.25145
title: Filipe Santos
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-62724694-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2e0093'
    - '#4f8ce2'
    - '#ffffff'
    - '#bfbfbf'
    - '#00ffff'
  brandStrength: 0.6403238931670785
  lightness: 0.6386932565364987
  saturation: 0.9085288278292865
  rhythmicContrast: 0.6290766329038888
purpose: []
